# Generated by Django 5.1.3 on 2024-11-18 11:41

import datetime
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DELIVERY', 'DELIVERY'), ('COMPLETED', 'COMPLETED')], default='ACCEPTED')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('SMARTPHONE', 'SMARTPHONE')])),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('image', models.ImageField(null=True, upload_to='products/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('address', models.CharField()),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['id'], name='shopapp_sto_id_4a2dfb_hash')],
            },
        ),
        migrations.CreateModel(
            name='StorageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.storage')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='shopapp_car_id_12e852_hash'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='shopapp_ord_id_fda4b7_hash'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='shopapp_pro_id_d923f9_hash'),
        ),
    ]
