# Generated by Django 5.1.3 on 2024-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT CONFIRMED', 'NOT CONFIRMED'), ('ACCEPTED', 'ACCEPTED'), ('DELIVERY', 'DELIVERY'), ('COMPLETED', 'COMPLETED')], default='NOT CONFIRMED'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
