# Generated by Django 5.1.3 on 2024-11-21 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_order_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 10, 37)),
        ),
    ]
