# Generated by Django 5.1.3 on 2024-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
