services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python /shop/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/shop 
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: {}

  
  