# Generated by Django 5.1.3 on 2024-11-11 08:47

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('SMARTPHONE', 'SMARTPHONE')])),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['id'], name='product_pro_id_b0dfc8_hash')],
            },
        ),
    ]
