# Generated by Django 5.1.3 on 2024-11-14 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DELIVERY', 'DELIVERY'), ('COMPLETED', 'COMPLETED')], default='ACCEPTED'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
