# Generated by Django 5.1.3 on 2024-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageproduct',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
